// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/connections": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/clients": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/interaction/:uid": {
    params: {
      "uid": string;
    };
  };
  "/register": {
    params: {};
  };
  "/register/method": {
    params: {};
  };
  "/register/setup": {
    params: {};
  };
  "/register/success": {
    params: {};
  };
  "/register/telegram-callback": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/connections" | "/admin" | "/admin/clients" | "/login" | "/interaction/:uid" | "/register" | "/register/method" | "/register/setup" | "/register/success" | "/register/telegram-callback";
  };
  "routes/RequireAuth.tsx": {
    id: "routes/RequireAuth";
    page: "/" | "/connections";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/connections.tsx": {
    id: "routes/connections";
    page: "/connections";
  };
  "routes/admin/layout.tsx": {
    id: "routes/admin/layout";
    page: "/admin" | "/admin/clients";
  };
  "routes/admin/members.tsx": {
    id: "routes/admin/members";
    page: "/admin";
  };
  "routes/admin/clients.tsx": {
    id: "routes/admin/clients";
    page: "/admin/clients";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/interaction.tsx": {
    id: "routes/interaction";
    page: "/interaction/:uid";
  };
  "routes/register/index.tsx": {
    id: "routes/register/index";
    page: "/register" | "/register/method" | "/register/setup" | "/register/success" | "/register/telegram-callback";
  };
  "routes/register/identity.tsx": {
    id: "routes/register/identity";
    page: "/register";
  };
  "routes/register/method.tsx": {
    id: "routes/register/method";
    page: "/register/method";
  };
  "routes/register/setup.tsx": {
    id: "routes/register/setup";
    page: "/register/setup";
  };
  "routes/register/success.tsx": {
    id: "routes/register/success";
    page: "/register/success";
  };
  "routes/register/telegram-callback.tsx": {
    id: "routes/register/telegram-callback";
    page: "/register/telegram-callback";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/RequireAuth": typeof import("./app/routes/RequireAuth.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/connections": typeof import("./app/routes/connections.tsx");
  "routes/admin/layout": typeof import("./app/routes/admin/layout.tsx");
  "routes/admin/members": typeof import("./app/routes/admin/members.tsx");
  "routes/admin/clients": typeof import("./app/routes/admin/clients.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/interaction": typeof import("./app/routes/interaction.tsx");
  "routes/register/index": typeof import("./app/routes/register/index.tsx");
  "routes/register/identity": typeof import("./app/routes/register/identity.tsx");
  "routes/register/method": typeof import("./app/routes/register/method.tsx");
  "routes/register/setup": typeof import("./app/routes/register/setup.tsx");
  "routes/register/success": typeof import("./app/routes/register/success.tsx");
  "routes/register/telegram-callback": typeof import("./app/routes/register/telegram-callback.tsx");
};