// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/register/method": {
    params: {};
  };
  "/register/setup": {
    params: {};
  };
  "/register/success": {
    params: {};
  };
  "/register/telegram-callback": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/register" | "/register/method" | "/register/setup" | "/register/success" | "/register/telegram-callback";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/register/index.tsx": {
    id: "routes/register/index";
    page: "/register" | "/register/method" | "/register/setup" | "/register/success" | "/register/telegram-callback";
  };
  "routes/register/identity.tsx": {
    id: "routes/register/identity";
    page: "/register";
  };
  "routes/register/method.tsx": {
    id: "routes/register/method";
    page: "/register/method";
  };
  "routes/register/setup.tsx": {
    id: "routes/register/setup";
    page: "/register/setup";
  };
  "routes/register/success.tsx": {
    id: "routes/register/success";
    page: "/register/success";
  };
  "routes/register/telegram-callback.tsx": {
    id: "routes/register/telegram-callback";
    page: "/register/telegram-callback";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/register/index": typeof import("./app/routes/register/index.tsx");
  "routes/register/identity": typeof import("./app/routes/register/identity.tsx");
  "routes/register/method": typeof import("./app/routes/register/method.tsx");
  "routes/register/setup": typeof import("./app/routes/register/setup.tsx");
  "routes/register/success": typeof import("./app/routes/register/success.tsx");
  "routes/register/telegram-callback": typeof import("./app/routes/register/telegram-callback.tsx");
};